// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final int CHASSIS_LEFT_FRONT_MOTOR_CAN_ID = 2;
    public static final int CHASSIS_LEFT_REAR_MOTOR_CAN_ID = 3;
    public static final int CHASSIS_RIGHT_FRONT_MOTOR_CAN_ID = 4;
    public static final int CHASSIS_RIGHT_REAR_MOTOR_CAN_ID = 5;
    public static final int ACQUISITION_SPIN_MOTOR_CAN_ID = 10;
    public static final int ACQUISITION_LOWER_MOTOR_CAN_ID = 11;
    public static final int STORAGE_MOTOR_CAN_ID = 12;
    public static final int LOADER_LEFT_BELT_MOTOR_CAN_ID = 20;
    public static final int LOADER_RIGHT_BELT_MOTOR_CAN_ID = 21;
    public static final int CLIMBER_LEFT_CLIMBER_MOTOR_CAN_ID = 22;
    public static final int CLIMBER_RIGHT_CLIMBER_MOTOR_CAN_ID = 24;
    public static final int SHOOTER_MOTOR_CAN_ID = 25;
}

