// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.firebears.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.firebears.Robot;
import edu.wpi.first.wpilibj.Preferences;

/**
 *
 */
public class DriveCommand extends Command {
  final Preferences config;
    int joystickSpeedAxis;
    int joystickRotateAxis;
    double adjust;

    public DriveCommand() {
      config = Preferences.getInstance();
        joystickSpeedAxis = config.getInt("joystick1.speedAxis", 1);
        joystickRotateAxis = config.getInt("joystick1.rotateAxis", 4);
        adjust = config.getDouble("driveCommand.deadBand", 0.1);
        requires(Robot.chassis);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
      double speed = -1 * Robot.oi.getXboxController().getRawAxis(joystickSpeedAxis);

      double rotation = Robot.oi.getXboxController().getRawAxis(joystickRotateAxis) * 0.7;
     Robot.chassis.drive((speed), (rotation));
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
