
package org.firebears.subsystems;

//import org.firebears.commands.*;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;
//import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
//import edu.wpi.first.wpilibj.PIDOutput;
//import edu.wpi.first.wpilibj.PIDSource;
import com.revrobotics.CANSparkMax;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;

import com.revrobotics.CANSparkMaxLowLevel.MotorType;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Acquisition extends SubsystemBase {

    static final Preferences config = Preferences.getInstance();

    private CANSparkMax lower;
    private CANSparkMax spin;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Acquisition() {

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        int acquisitionLowerCanID = config.getInt("acquisition.lower.canID", 2);
        lower = new CANSparkMax(acquisitionLowerCanID, MotorType.kBrushless);
        lower.setInverted(false);

        int acquisitionSpinCanID = config.getInt("acquisition.spin.canID", 6);
        spin = new CANSparkMax(acquisitionSpinCanID, MotorType.kBrushless);
        spin.setInverted(false);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        SmartDashboard.putNumber("lowerSpeed", lower.get());
        SmartDashboard.putNumber("spinSpeed", spin.get());

        // Put code here to be run every loop

    }

    public void startAcquire() {
        lower.set(1);
        spin.set(1);
    }

    public void endAcquire() {
        lower.set(-1);
        spin.set(-1);
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
